<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>5</Version>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Identity" Version="1.14.2" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.7" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.7" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
      <PackageReference Include="Microsoft.Graph" Version="5.86.0" />
      <PackageReference Include="MimeKit" Version="4.13.0" />
      <PackageReference Include="Serilog" Version="4.3.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
      <PackageReference Include="SmtpServer" Version="11.0.0" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
